### ISSUE TITLE
Maybe ignore phpunit.xml?

### ISSUE THREAD

**Issue by Quix0r** [FrescoPHP/fresco#1]
There is `phpunit.xml.dist` which can be easily duplicated to `phpunit.xml` which then can be customized locally. To prevent a developer from accidentally adding it to the repository (with local customizing) it is common to ignore the file.

**Comment by patrickbrouwers** [comment]
Hey @Quix0r I don't think anybody uses this project. At least it's not installable via packagist. It was just an experiment of a few years back. Wouldn't recommend using it.

**Comment by Quix0r** [comment]
Okay.
